/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    isProgramError,
    type Address,
    type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
    type SolanaError,
} from '@solana/kit';
import { TOKEN_PROGRAM_ADDRESS } from '../programs/index.js';

/** ProofVerificationFailed: SP1 Groth16 proof verification failed */
export const TOKEN_ERROR__PROOF_VERIFICATION_FAILED = 0x1770; // 6000
/** DecodingProofFailed: Failed to decode proof bytes */
export const TOKEN_ERROR__DECODING_PROOF_FAILED = 0x1771; // 6001
/** ETHProofQueueAddressMismatch: ETH proof queue address mismatch */
export const TOKEN_ERROR__E_T_H_PROOF_QUEUE_ADDRESS_MISMATCH = 0x1772; // 6002
/** QueueCursorMismatch: Queue cursor mismatch */
export const TOKEN_ERROR__QUEUE_CURSOR_MISMATCH = 0x1773; // 6003
/** InputSlotMismatch: Input slot does not match latest verified head */
export const TOKEN_ERROR__INPUT_SLOT_MISMATCH = 0x1774; // 6004
/** InputStoreHashMismatch: Input store hash does not match latest verified store hash */
export const TOKEN_ERROR__INPUT_STORE_HASH_MISMATCH = 0x1775; // 6005
/** InvalidOutputSlot: Output slot is not greater than input slot */
export const TOKEN_ERROR__INVALID_OUTPUT_SLOT = 0x1776; // 6006
/** ZeroSyncCommitteeHash: Next sync committee hash is zero */
export const TOKEN_ERROR__ZERO_SYNC_COMMITTEE_HASH = 0x1777; // 6007
/** ProofQueueBatchAccountMismatch: Proof queue batch account is not the PDA for the next proof queue batch index */
export const TOKEN_ERROR__PROOF_QUEUE_BATCH_ACCOUNT_MISMATCH = 0x1778; // 6008
/** NotTokenBridgeRequest: VerifiedRequest is not a proof of state for the token bridge contract */
export const TOKEN_ERROR__NOT_TOKEN_BRIDGE_REQUEST = 0x1779; // 6009
/** MintedExceedsLocked: locked_so_far is less than minted_so_far; this would cause a negative mint amount */
export const TOKEN_ERROR__MINTED_EXCEEDS_LOCKED = 0x177a; // 6010
/** ZeroMintAmount: No new amount to mint: locked_so_far equals minted_so_far */
export const TOKEN_ERROR__ZERO_MINT_AMOUNT = 0x177b; // 6011
/** LockedAmountOverflow: Locked amount does not fit in a u64 token amount */
export const TOKEN_ERROR__LOCKED_AMOUNT_OVERFLOW = 0x177c; // 6012
/** CommitmentMismatch: Recipient pubkey does not hash to the deposit commitment */
export const TOKEN_ERROR__COMMITMENT_MISMATCH = 0x177d; // 6013
/** ProofQueueBatchRootMismatch: Witness root does not match the committed proof queue batch root */
export const TOKEN_ERROR__PROOF_QUEUE_BATCH_ROOT_MISMATCH = 0x177e; // 6014
/** WitnessIndexOutsideProofQueueBatch: Witness index is outside the committed proof queue batch */
export const TOKEN_ERROR__WITNESS_INDEX_OUTSIDE_PROOF_QUEUE_BATCH = 0x177f; // 6015
/** InvalidDepositWitness: Deposit witness is malformed */
export const TOKEN_ERROR__INVALID_DEPOSIT_WITNESS = 0x1780; // 6016

export type TokenError =
    | typeof TOKEN_ERROR__COMMITMENT_MISMATCH
    | typeof TOKEN_ERROR__DECODING_PROOF_FAILED
    | typeof TOKEN_ERROR__E_T_H_PROOF_QUEUE_ADDRESS_MISMATCH
    | typeof TOKEN_ERROR__INPUT_SLOT_MISMATCH
    | typeof TOKEN_ERROR__INPUT_STORE_HASH_MISMATCH
    | typeof TOKEN_ERROR__INVALID_DEPOSIT_WITNESS
    | typeof TOKEN_ERROR__INVALID_OUTPUT_SLOT
    | typeof TOKEN_ERROR__LOCKED_AMOUNT_OVERFLOW
    | typeof TOKEN_ERROR__MINTED_EXCEEDS_LOCKED
    | typeof TOKEN_ERROR__NOT_TOKEN_BRIDGE_REQUEST
    | typeof TOKEN_ERROR__PROOF_QUEUE_BATCH_ACCOUNT_MISMATCH
    | typeof TOKEN_ERROR__PROOF_QUEUE_BATCH_ROOT_MISMATCH
    | typeof TOKEN_ERROR__PROOF_VERIFICATION_FAILED
    | typeof TOKEN_ERROR__QUEUE_CURSOR_MISMATCH
    | typeof TOKEN_ERROR__WITNESS_INDEX_OUTSIDE_PROOF_QUEUE_BATCH
    | typeof TOKEN_ERROR__ZERO_MINT_AMOUNT
    | typeof TOKEN_ERROR__ZERO_SYNC_COMMITTEE_HASH;

let tokenErrorMessages: Record<TokenError, string> | undefined;
if (process.env['NODE_ENV'] !== 'production') {
    tokenErrorMessages = {
        [TOKEN_ERROR__COMMITMENT_MISMATCH]: `Recipient pubkey does not hash to the deposit commitment`,
        [TOKEN_ERROR__DECODING_PROOF_FAILED]: `Failed to decode proof bytes`,
        [TOKEN_ERROR__E_T_H_PROOF_QUEUE_ADDRESS_MISMATCH]: `ETH proof queue address mismatch`,
        [TOKEN_ERROR__INPUT_SLOT_MISMATCH]: `Input slot does not match latest verified head`,
        [TOKEN_ERROR__INPUT_STORE_HASH_MISMATCH]: `Input store hash does not match latest verified store hash`,
        [TOKEN_ERROR__INVALID_DEPOSIT_WITNESS]: `Deposit witness is malformed`,
        [TOKEN_ERROR__INVALID_OUTPUT_SLOT]: `Output slot is not greater than input slot`,
        [TOKEN_ERROR__LOCKED_AMOUNT_OVERFLOW]: `Locked amount does not fit in a u64 token amount`,
        [TOKEN_ERROR__MINTED_EXCEEDS_LOCKED]: `locked_so_far is less than minted_so_far; this would cause a negative mint amount`,
        [TOKEN_ERROR__NOT_TOKEN_BRIDGE_REQUEST]: `VerifiedRequest is not a proof of state for the token bridge contract`,
        [TOKEN_ERROR__PROOF_QUEUE_BATCH_ACCOUNT_MISMATCH]: `Proof queue batch account is not the PDA for the next proof queue batch index`,
        [TOKEN_ERROR__PROOF_QUEUE_BATCH_ROOT_MISMATCH]: `Witness root does not match the committed proof queue batch root`,
        [TOKEN_ERROR__PROOF_VERIFICATION_FAILED]: `SP1 Groth16 proof verification failed`,
        [TOKEN_ERROR__QUEUE_CURSOR_MISMATCH]: `Queue cursor mismatch`,
        [TOKEN_ERROR__WITNESS_INDEX_OUTSIDE_PROOF_QUEUE_BATCH]: `Witness index is outside the committed proof queue batch`,
        [TOKEN_ERROR__ZERO_MINT_AMOUNT]: `No new amount to mint: locked_so_far equals minted_so_far`,
        [TOKEN_ERROR__ZERO_SYNC_COMMITTEE_HASH]: `Next sync committee hash is zero`,
    };
}

export function getTokenErrorMessage(code: TokenError): string {
    if (process.env['NODE_ENV'] !== 'production') {
        return (tokenErrorMessages as Record<TokenError, string>)[code];
    }

    return 'Error message not available in production bundles.';
}

export function isTokenError<TProgramErrorCode extends TokenError>(
    error: unknown,
    transactionMessage: {
        instructions: Record<number, { programAddress: Address }>;
    },
    code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
    Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
    return isProgramError<TProgramErrorCode>(
        error,
        transactionMessage,
        TOKEN_PROGRAM_ADDRESS,
        code
    );
}
