/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    assertAccountExists,
    assertAccountsExist,
    combineCodec,
    decodeAccount,
    fetchEncodedAccount,
    fetchEncodedAccounts,
    fixDecoderSize,
    fixEncoderSize,
    getAddressDecoder,
    getAddressEncoder,
    getBytesDecoder,
    getBytesEncoder,
    getStructDecoder,
    getStructEncoder,
    getU64Decoder,
    getU64Encoder,
    transformEncoder,
    type Account,
    type Address,
    type EncodedAccount,
    type FetchAccountConfig,
    type FetchAccountsConfig,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type MaybeAccount,
    type MaybeEncodedAccount,
    type ReadonlyUint8Array,
} from '@solana/kit';

export const NORI_SOL_TOKEN_BRIDGE_DISCRIMINATOR: ReadonlyUint8Array =
    new Uint8Array([156, 61, 33, 52, 224, 168, 181, 250]);

export function getNoriSolTokenBridgeDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(
        NORI_SOL_TOKEN_BRIDGE_DISCRIMINATOR
    );
}

export type NoriSolTokenBridge = {
    discriminator: ReadonlyUint8Array;
    authority: Address;
    verifiedStateRoot: ReadonlyUint8Array;
    latestHead: bigint;
    noriBridgeVk: ReadonlyUint8Array;
    latestHeliosStoreInputHash: ReadonlyUint8Array;
    ethProofQueueAddress: ReadonlyUint8Array;
    ethTokenBridgeAddress: ReadonlyUint8Array;
    queueCursor: bigint;
    proofQueueBatchCount: bigint;
};

export type NoriSolTokenBridgeArgs = {
    authority: Address;
    verifiedStateRoot: ReadonlyUint8Array;
    latestHead: number | bigint;
    noriBridgeVk: ReadonlyUint8Array;
    latestHeliosStoreInputHash: ReadonlyUint8Array;
    ethProofQueueAddress: ReadonlyUint8Array;
    ethTokenBridgeAddress: ReadonlyUint8Array;
    queueCursor: number | bigint;
    proofQueueBatchCount: number | bigint;
};

/** Gets the encoder for {@link NoriSolTokenBridgeArgs} account data. */
export function getNoriSolTokenBridgeEncoder(): FixedSizeEncoder<NoriSolTokenBridgeArgs> {
    return transformEncoder(
        getStructEncoder([
            ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
            ['authority', getAddressEncoder()],
            ['verifiedStateRoot', fixEncoderSize(getBytesEncoder(), 32)],
            ['latestHead', getU64Encoder()],
            ['noriBridgeVk', fixEncoderSize(getBytesEncoder(), 32)],
            [
                'latestHeliosStoreInputHash',
                fixEncoderSize(getBytesEncoder(), 32),
            ],
            ['ethProofQueueAddress', fixEncoderSize(getBytesEncoder(), 20)],
            ['ethTokenBridgeAddress', fixEncoderSize(getBytesEncoder(), 20)],
            ['queueCursor', getU64Encoder()],
            ['proofQueueBatchCount', getU64Encoder()],
        ]),
        (value) => ({
            ...value,
            discriminator: NORI_SOL_TOKEN_BRIDGE_DISCRIMINATOR,
        })
    );
}

/** Gets the decoder for {@link NoriSolTokenBridge} account data. */
export function getNoriSolTokenBridgeDecoder(): FixedSizeDecoder<NoriSolTokenBridge> {
    return getStructDecoder([
        ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
        ['authority', getAddressDecoder()],
        ['verifiedStateRoot', fixDecoderSize(getBytesDecoder(), 32)],
        ['latestHead', getU64Decoder()],
        ['noriBridgeVk', fixDecoderSize(getBytesDecoder(), 32)],
        ['latestHeliosStoreInputHash', fixDecoderSize(getBytesDecoder(), 32)],
        ['ethProofQueueAddress', fixDecoderSize(getBytesDecoder(), 20)],
        ['ethTokenBridgeAddress', fixDecoderSize(getBytesDecoder(), 20)],
        ['queueCursor', getU64Decoder()],
        ['proofQueueBatchCount', getU64Decoder()],
    ]);
}

/** Gets the codec for {@link NoriSolTokenBridge} account data. */
export function getNoriSolTokenBridgeCodec(): FixedSizeCodec<
    NoriSolTokenBridgeArgs,
    NoriSolTokenBridge
> {
    return combineCodec(
        getNoriSolTokenBridgeEncoder(),
        getNoriSolTokenBridgeDecoder()
    );
}

export function decodeNoriSolTokenBridge<TAddress extends string = string>(
    encodedAccount: EncodedAccount<TAddress>
): Account<NoriSolTokenBridge, TAddress>;
export function decodeNoriSolTokenBridge<TAddress extends string = string>(
    encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<NoriSolTokenBridge, TAddress>;
export function decodeNoriSolTokenBridge<TAddress extends string = string>(
    encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
    | Account<NoriSolTokenBridge, TAddress>
    | MaybeAccount<NoriSolTokenBridge, TAddress> {
    return decodeAccount(
        encodedAccount as MaybeEncodedAccount<TAddress>,
        getNoriSolTokenBridgeDecoder()
    );
}

export async function fetchNoriSolTokenBridge<TAddress extends string = string>(
    rpc: Parameters<typeof fetchEncodedAccount>[0],
    address: Address<TAddress>,
    config?: FetchAccountConfig
): Promise<Account<NoriSolTokenBridge, TAddress>> {
    const maybeAccount = await fetchMaybeNoriSolTokenBridge(
        rpc,
        address,
        config
    );
    assertAccountExists(maybeAccount);
    return maybeAccount;
}

export async function fetchMaybeNoriSolTokenBridge<
    TAddress extends string = string,
>(
    rpc: Parameters<typeof fetchEncodedAccount>[0],
    address: Address<TAddress>,
    config?: FetchAccountConfig
): Promise<MaybeAccount<NoriSolTokenBridge, TAddress>> {
    const maybeAccount = await fetchEncodedAccount(rpc, address, config);
    return decodeNoriSolTokenBridge(maybeAccount);
}

export async function fetchAllNoriSolTokenBridge(
    rpc: Parameters<typeof fetchEncodedAccounts>[0],
    addresses: Array<Address>,
    config?: FetchAccountsConfig
): Promise<Account<NoriSolTokenBridge>[]> {
    const maybeAccounts = await fetchAllMaybeNoriSolTokenBridge(
        rpc,
        addresses,
        config
    );
    assertAccountsExist(maybeAccounts);
    return maybeAccounts;
}

export async function fetchAllMaybeNoriSolTokenBridge(
    rpc: Parameters<typeof fetchEncodedAccounts>[0],
    addresses: Array<Address>,
    config?: FetchAccountsConfig
): Promise<MaybeAccount<NoriSolTokenBridge>[]> {
    const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
    return maybeAccounts.map((maybeAccount) =>
        decodeNoriSolTokenBridge(maybeAccount)
    );
}

export function getNoriSolTokenBridgeSize(): number {
    return 200;
}
