/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    assertAccountExists,
    assertAccountsExist,
    combineCodec,
    decodeAccount,
    fetchEncodedAccount,
    fetchEncodedAccounts,
    fixDecoderSize,
    fixEncoderSize,
    getBytesDecoder,
    getBytesEncoder,
    getStructDecoder,
    getStructEncoder,
    getU64Decoder,
    getU64Encoder,
    transformEncoder,
    type Account,
    type Address,
    type EncodedAccount,
    type FetchAccountConfig,
    type FetchAccountsConfig,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type MaybeAccount,
    type MaybeEncodedAccount,
    type ReadonlyUint8Array,
} from '@solana/kit';

export const PROOF_REQUEST_ROOT_ENTRY_DISCRIMINATOR: ReadonlyUint8Array =
    new Uint8Array([118, 111, 5, 174, 165, 184, 191, 96]);

export function getProofRequestRootEntryDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(
        PROOF_REQUEST_ROOT_ENTRY_DISCRIMINATOR
    );
}

export type ProofRequestRootEntry = {
    discriminator: ReadonlyUint8Array;
    root: ReadonlyUint8Array;
    outputBlockNumber: bigint;
    inputQueueCursor: bigint;
    outputQueueCursor: bigint;
};

export type ProofRequestRootEntryArgs = {
    root: ReadonlyUint8Array;
    outputBlockNumber: number | bigint;
    inputQueueCursor: number | bigint;
    outputQueueCursor: number | bigint;
};

/** Gets the encoder for {@link ProofRequestRootEntryArgs} account data. */
export function getProofRequestRootEntryEncoder(): FixedSizeEncoder<ProofRequestRootEntryArgs> {
    return transformEncoder(
        getStructEncoder([
            ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
            ['root', fixEncoderSize(getBytesEncoder(), 32)],
            ['outputBlockNumber', getU64Encoder()],
            ['inputQueueCursor', getU64Encoder()],
            ['outputQueueCursor', getU64Encoder()],
        ]),
        (value) => ({
            ...value,
            discriminator: PROOF_REQUEST_ROOT_ENTRY_DISCRIMINATOR,
        })
    );
}

/** Gets the decoder for {@link ProofRequestRootEntry} account data. */
export function getProofRequestRootEntryDecoder(): FixedSizeDecoder<ProofRequestRootEntry> {
    return getStructDecoder([
        ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
        ['root', fixDecoderSize(getBytesDecoder(), 32)],
        ['outputBlockNumber', getU64Decoder()],
        ['inputQueueCursor', getU64Decoder()],
        ['outputQueueCursor', getU64Decoder()],
    ]);
}

/** Gets the codec for {@link ProofRequestRootEntry} account data. */
export function getProofRequestRootEntryCodec(): FixedSizeCodec<
    ProofRequestRootEntryArgs,
    ProofRequestRootEntry
> {
    return combineCodec(
        getProofRequestRootEntryEncoder(),
        getProofRequestRootEntryDecoder()
    );
}

export function decodeProofRequestRootEntry<TAddress extends string = string>(
    encodedAccount: EncodedAccount<TAddress>
): Account<ProofRequestRootEntry, TAddress>;
export function decodeProofRequestRootEntry<TAddress extends string = string>(
    encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<ProofRequestRootEntry, TAddress>;
export function decodeProofRequestRootEntry<TAddress extends string = string>(
    encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
    | Account<ProofRequestRootEntry, TAddress>
    | MaybeAccount<ProofRequestRootEntry, TAddress> {
    return decodeAccount(
        encodedAccount as MaybeEncodedAccount<TAddress>,
        getProofRequestRootEntryDecoder()
    );
}

export async function fetchProofRequestRootEntry<
    TAddress extends string = string,
>(
    rpc: Parameters<typeof fetchEncodedAccount>[0],
    address: Address<TAddress>,
    config?: FetchAccountConfig
): Promise<Account<ProofRequestRootEntry, TAddress>> {
    const maybeAccount = await fetchMaybeProofRequestRootEntry(
        rpc,
        address,
        config
    );
    assertAccountExists(maybeAccount);
    return maybeAccount;
}

export async function fetchMaybeProofRequestRootEntry<
    TAddress extends string = string,
>(
    rpc: Parameters<typeof fetchEncodedAccount>[0],
    address: Address<TAddress>,
    config?: FetchAccountConfig
): Promise<MaybeAccount<ProofRequestRootEntry, TAddress>> {
    const maybeAccount = await fetchEncodedAccount(rpc, address, config);
    return decodeProofRequestRootEntry(maybeAccount);
}

export async function fetchAllProofRequestRootEntry(
    rpc: Parameters<typeof fetchEncodedAccounts>[0],
    addresses: Array<Address>,
    config?: FetchAccountsConfig
): Promise<Account<ProofRequestRootEntry>[]> {
    const maybeAccounts = await fetchAllMaybeProofRequestRootEntry(
        rpc,
        addresses,
        config
    );
    assertAccountsExist(maybeAccounts);
    return maybeAccounts;
}

export async function fetchAllMaybeProofRequestRootEntry(
    rpc: Parameters<typeof fetchEncodedAccounts>[0],
    addresses: Array<Address>,
    config?: FetchAccountsConfig
): Promise<MaybeAccount<ProofRequestRootEntry>[]> {
    const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
    return maybeAccounts.map((maybeAccount) =>
        decodeProofRequestRootEntry(maybeAccount)
    );
}

export function getProofRequestRootEntrySize(): number {
    return 64;
}
