/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    getAddressEncoder,
    getBytesEncoder,
    getProgramDerivedAddress,
    type Address,
    type ProgramDerivedAddress,
} from '@solana/kit';

export type TokenAccountStorageSeeds = {
    recipient: Address;
};

export async function findTokenAccountStoragePda(
    seeds: TokenAccountStorageSeeds,
    config: { programAddress?: Address | undefined } = {}
): Promise<ProgramDerivedAddress> {
    const {
        programAddress = 'EUz5RMQxYkc9zu12wpCDu9syvr4MarghoYb6jHAvdAcg' as Address<'EUz5RMQxYkc9zu12wpCDu9syvr4MarghoYb6jHAvdAcg'>,
    } = config;
    return await getProgramDerivedAddress({
        programAddress,
        seeds: [
            getBytesEncoder().encode(
                new Uint8Array([83, 84, 79, 82, 65, 71, 69])
            ),
            getAddressEncoder().encode(seeds.recipient),
        ],
    });
}
