/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    getBytesEncoder,
    getProgramDerivedAddress,
    type Address,
    type ProgramDerivedAddress,
} from '@solana/kit';

export async function findTokenPda(
    config: { programAddress?: Address | undefined } = {}
): Promise<ProgramDerivedAddress> {
    const {
        programAddress = '5xS32i7XNRk7JCjYR7RgfHVxdLepVSnnJ1gdHkmfD8W1' as Address<'5xS32i7XNRk7JCjYR7RgfHVxdLepVSnnJ1gdHkmfD8W1'>,
    } = config;
    return await getProgramDerivedAddress({
        programAddress,
        seeds: [getBytesEncoder().encode(new Uint8Array([78, 69, 84, 72]))],
    });
}
