/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    assertIsInstructionWithAccounts,
    containsBytes,
    extendClient,
    fixEncoderSize,
    getBytesEncoder,
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
    SolanaError,
    type Address,
    type ClientWithPayer,
    type ClientWithRpc,
    type ClientWithTransactionPlanning,
    type ClientWithTransactionSending,
    type ExtendedClient,
    type GetAccountInfoApi,
    type GetMultipleAccountsApi,
    type Instruction,
    type InstructionWithData,
    type ReadonlyUint8Array,
} from '@solana/kit';
import {
    addSelfFetchFunctions,
    addSelfPlanAndSendFunctions,
    type SelfFetchFunctions,
    type SelfPlanAndSendFunctions,
} from '@solana/program-client-core';
import {
    getNoriSolTokenBridgeCodec,
    getProofRequestRootEntryCodec,
    type NoriSolTokenBridge,
    type NoriSolTokenBridgeArgs,
    type ProofRequestRootEntry,
    type ProofRequestRootEntryArgs,
} from '../accounts/index.js';
import {
    getInitializeInstructionAsync,
    getMintInstructionAsync,
    getUpdateInstructionAsync,
    parseInitializeInstruction,
    parseMintInstruction,
    parseUpdateInstruction,
    type InitializeAsyncInput,
    type MintAsyncInput,
    type ParsedInitializeInstruction,
    type ParsedMintInstruction,
    type ParsedUpdateInstruction,
    type UpdateAsyncInput,
} from '../instructions/index.js';
import {
    findStatePda,
    findTokenAccountStoragePda,
    findTokenPda,
} from '../pdas/index.js';

export const TOKEN_PROGRAM_ADDRESS =
    'EUz5RMQxYkc9zu12wpCDu9syvr4MarghoYb6jHAvdAcg' as Address<'EUz5RMQxYkc9zu12wpCDu9syvr4MarghoYb6jHAvdAcg'>;

export enum TokenAccount {
    NoriSolTokenBridge,
    ProofRequestRootEntry,
}

export function identifyTokenAccount(
    account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): TokenAccount {
    const data = 'data' in account ? account.data : account;
    if (
        containsBytes(
            data,
            fixEncoderSize(getBytesEncoder(), 8).encode(
                new Uint8Array([156, 61, 33, 52, 224, 168, 181, 250])
            ),
            0
        )
    ) {
        return TokenAccount.NoriSolTokenBridge;
    }
    if (
        containsBytes(
            data,
            fixEncoderSize(getBytesEncoder(), 8).encode(
                new Uint8Array([118, 111, 5, 174, 165, 184, 191, 96])
            ),
            0
        )
    ) {
        return TokenAccount.ProofRequestRootEntry;
    }
    throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
        { accountData: data, programName: 'token' }
    );
}

export enum TokenEvent {
    MintApplied,
    UpdateApplied,
}

export function identifyTokenEvent(
    event: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): TokenEvent {
    const data = 'data' in event ? event.data : event;
    if (
        containsBytes(
            data,
            fixEncoderSize(getBytesEncoder(), 8).encode(
                new Uint8Array([167, 56, 99, 198, 217, 201, 142, 66])
            ),
            0
        )
    ) {
        return TokenEvent.MintApplied;
    }
    if (
        containsBytes(
            data,
            fixEncoderSize(getBytesEncoder(), 8).encode(
                new Uint8Array([230, 193, 225, 238, 5, 232, 91, 236])
            ),
            0
        )
    ) {
        return TokenEvent.UpdateApplied;
    }
    throw new Error(
        'The provided event could not be identified as a token event.'
    );
}

export enum TokenInstruction {
    Initialize,
    Mint,
    Update,
}

export function identifyTokenInstruction(
    instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): TokenInstruction {
    const data = 'data' in instruction ? instruction.data : instruction;
    if (
        containsBytes(
            data,
            fixEncoderSize(getBytesEncoder(), 8).encode(
                new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237])
            ),
            0
        )
    ) {
        return TokenInstruction.Initialize;
    }
    if (
        containsBytes(
            data,
            fixEncoderSize(getBytesEncoder(), 8).encode(
                new Uint8Array([51, 57, 225, 47, 182, 146, 137, 166])
            ),
            0
        )
    ) {
        return TokenInstruction.Mint;
    }
    if (
        containsBytes(
            data,
            fixEncoderSize(getBytesEncoder(), 8).encode(
                new Uint8Array([219, 200, 88, 176, 158, 63, 253, 127])
            ),
            0
        )
    ) {
        return TokenInstruction.Update;
    }
    throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
        { instructionData: data, programName: 'token' }
    );
}

export type ParsedTokenInstruction<
    TProgram extends string = 'EUz5RMQxYkc9zu12wpCDu9syvr4MarghoYb6jHAvdAcg',
> =
    | ({
          instructionType: TokenInstruction.Initialize;
      } & ParsedInitializeInstruction<TProgram>)
    | ({
          instructionType: TokenInstruction.Mint;
      } & ParsedMintInstruction<TProgram>)
    | ({
          instructionType: TokenInstruction.Update;
      } & ParsedUpdateInstruction<TProgram>);

export function parseTokenInstruction<TProgram extends string>(
    instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>
): ParsedTokenInstruction<TProgram> {
    const instructionType = identifyTokenInstruction(instruction);
    switch (instructionType) {
        case TokenInstruction.Initialize: {
            assertIsInstructionWithAccounts(instruction);
            return {
                instructionType: TokenInstruction.Initialize,
                ...parseInitializeInstruction(instruction),
            };
        }
        case TokenInstruction.Mint: {
            assertIsInstructionWithAccounts(instruction);
            return {
                instructionType: TokenInstruction.Mint,
                ...parseMintInstruction(instruction),
            };
        }
        case TokenInstruction.Update: {
            assertIsInstructionWithAccounts(instruction);
            return {
                instructionType: TokenInstruction.Update,
                ...parseUpdateInstruction(instruction),
            };
        }
        default:
            throw new SolanaError(
                SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
                {
                    instructionType: instructionType as string,
                    programName: 'token',
                }
            );
    }
}

export type TokenPlugin = {
    accounts: TokenPluginAccounts;
    instructions: TokenPluginInstructions;
    pdas: TokenPluginPdas;
    identifyAccount: typeof identifyTokenAccount;
    identifyInstruction: typeof identifyTokenInstruction;
    parseInstruction: typeof parseTokenInstruction;
};

export type TokenPluginAccounts = {
    noriSolTokenBridge: ReturnType<typeof getNoriSolTokenBridgeCodec> &
        SelfFetchFunctions<NoriSolTokenBridgeArgs, NoriSolTokenBridge>;
    proofRequestRootEntry: ReturnType<typeof getProofRequestRootEntryCodec> &
        SelfFetchFunctions<ProofRequestRootEntryArgs, ProofRequestRootEntry>;
};

export type TokenPluginInstructions = {
    initialize: (
        input: MakeOptional<InitializeAsyncInput, 'payer'>
    ) => ReturnType<typeof getInitializeInstructionAsync> &
        SelfPlanAndSendFunctions;
    mint: (
        input: MakeOptional<MintAsyncInput, 'payer'>
    ) => ReturnType<typeof getMintInstructionAsync> & SelfPlanAndSendFunctions;
    update: (
        input: MakeOptional<UpdateAsyncInput, 'payer'>
    ) => ReturnType<typeof getUpdateInstructionAsync> &
        SelfPlanAndSendFunctions;
};

export type TokenPluginPdas = {
    state: typeof findStatePda;
    token: typeof findTokenPda;
    tokenAccountStorage: typeof findTokenAccountStoragePda;
};

export type TokenPluginRequirements = ClientWithRpc<
    GetAccountInfoApi & GetMultipleAccountsApi
> &
    ClientWithPayer &
    ClientWithTransactionPlanning &
    ClientWithTransactionSending;

export function tokenProgram() {
    return <T extends TokenPluginRequirements>(
        client: T
    ): ExtendedClient<T, { token: TokenPlugin }> => {
        return extendClient(client, {
            token: <TokenPlugin>{
                accounts: {
                    noriSolTokenBridge: addSelfFetchFunctions(
                        client,
                        getNoriSolTokenBridgeCodec()
                    ),
                    proofRequestRootEntry: addSelfFetchFunctions(
                        client,
                        getProofRequestRootEntryCodec()
                    ),
                },
                instructions: {
                    initialize: (input) =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getInitializeInstructionAsync({
                                ...input,
                                payer: input.payer ?? client.payer,
                            })
                        ),
                    mint: (input) =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getMintInstructionAsync({
                                ...input,
                                payer: input.payer ?? client.payer,
                            })
                        ),
                    update: (input) =>
                        addSelfPlanAndSendFunctions(
                            client,
                            getUpdateInstructionAsync({
                                ...input,
                                payer: input.payer ?? client.payer,
                            })
                        ),
                },
                pdas: {
                    state: findStatePda,
                    token: findTokenPda,
                    tokenAccountStorage: findTokenAccountStoragePda,
                },
                identifyAccount: identifyTokenAccount,
                identifyInstruction: identifyTokenInstruction,
                parseInstruction: parseTokenInstruction,
            },
        });
    };
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
