/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type { ReadonlyUint8Array } from '@solana/kit';

export const NORI_SOL_TOKEN_ACCOUNT_STORAGE_SEED: ReadonlyUint8Array =
    new Uint8Array([83, 84, 79, 82, 65, 71, 69]);

export const NORI_SOL_TOKEN_BRIDGE_PROOF_QUEUE_BATCH_SEED: ReadonlyUint8Array =
    new Uint8Array([
        80, 82, 79, 79, 70, 95, 81, 85, 69, 85, 69, 95, 66, 65, 84, 67, 72,
    ]);

export const NORI_SOL_TOKEN_BRIDGE_SEED: ReadonlyUint8Array = new Uint8Array([
    78, 69, 84, 72,
]);

export const NORI_SOL_TOKEN_BRIDGE_STATE_SEED: ReadonlyUint8Array =
    new Uint8Array([83, 84, 65, 84, 69]);

export const TOKEN_DECIMALS: number = 6;
