/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    combineCodec,
    containsBytes,
    fixDecoderSize,
    fixEncoderSize,
    getAddressDecoder,
    getAddressEncoder,
    getBytesDecoder,
    getBytesEncoder,
    getConstantDecoder,
    getConstantEncoder,
    getHiddenPrefixDecoder,
    getHiddenPrefixEncoder,
    getStructDecoder,
    getStructEncoder,
    getU64Decoder,
    getU64Encoder,
    type Address,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type ReadonlyUint8Array,
} from '@solana/kit';

export const MINT_APPLIED_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
    new Uint8Array([167, 56, 99, 198, 217, 201, 142, 66]);

export function getMintAppliedEventDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(
        MINT_APPLIED_EVENT_DISCRIMINATOR
    );
}

export type MintAppliedEvent = {
    recipient: Address;
    depositRoot: ReadonlyUint8Array;
    amountMinted: bigint;
    mintedSoFar: bigint;
};

export type MintAppliedEventArgs = {
    recipient: Address;
    depositRoot: ReadonlyUint8Array;
    amountMinted: number | bigint;
    mintedSoFar: number | bigint;
};

/** Gets the encoder for {@link MintAppliedEventArgs} event data. */
export function getMintAppliedEventEncoder(): FixedSizeEncoder<MintAppliedEventArgs> {
    return getHiddenPrefixEncoder(
        getStructEncoder([
            ['recipient', getAddressEncoder()],
            ['depositRoot', fixEncoderSize(getBytesEncoder(), 32)],
            ['amountMinted', getU64Encoder()],
            ['mintedSoFar', getU64Encoder()],
        ]),
        [getConstantEncoder(MINT_APPLIED_EVENT_DISCRIMINATOR)]
    );
}

/** Gets the decoder for {@link MintAppliedEvent} event data. */
export function getMintAppliedEventDecoder(): FixedSizeDecoder<MintAppliedEvent> {
    return getHiddenPrefixDecoder(
        getStructDecoder([
            ['recipient', getAddressDecoder()],
            ['depositRoot', fixDecoderSize(getBytesDecoder(), 32)],
            ['amountMinted', getU64Decoder()],
            ['mintedSoFar', getU64Decoder()],
        ]),
        [getConstantDecoder(MINT_APPLIED_EVENT_DISCRIMINATOR)]
    );
}

/** Gets the codec for {@link MintAppliedEvent} event data. */
export function getMintAppliedEventCodec(): FixedSizeCodec<
    MintAppliedEventArgs,
    MintAppliedEvent
> {
    return combineCodec(
        getMintAppliedEventEncoder(),
        getMintAppliedEventDecoder()
    );
}

/** Parses the provided bytes into {@link MintAppliedEvent} event data. */
export function parseMintAppliedEvent(
    data: ReadonlyUint8Array | Uint8Array
): MintAppliedEvent {
    if (containsBytes(data, MINT_APPLIED_EVENT_DISCRIMINATOR, 0)) {
        return getMintAppliedEventDecoder().decode(data);
    }
    throw new Error(
        'The provided data does not match the "MintAppliedEvent" event discriminators.'
    );
}
