/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    combineCodec,
    containsBytes,
    fixDecoderSize,
    fixEncoderSize,
    getBytesDecoder,
    getBytesEncoder,
    getConstantDecoder,
    getConstantEncoder,
    getHiddenPrefixDecoder,
    getHiddenPrefixEncoder,
    getStructDecoder,
    getStructEncoder,
    getU64Decoder,
    getU64Encoder,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type ReadonlyUint8Array,
} from '@solana/kit';

export const UPDATE_APPLIED_EVENT_DISCRIMINATOR: ReadonlyUint8Array =
    new Uint8Array([230, 193, 225, 238, 5, 232, 91, 236]);

export function getUpdateAppliedEventDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(
        UPDATE_APPLIED_EVENT_DISCRIMINATOR
    );
}

export type UpdateAppliedEvent = {
    outputSlot: bigint;
    queueCursor: bigint;
    verifiedStateRoot: ReadonlyUint8Array;
    proofQueueBatchCount: bigint;
};

export type UpdateAppliedEventArgs = {
    outputSlot: number | bigint;
    queueCursor: number | bigint;
    verifiedStateRoot: ReadonlyUint8Array;
    proofQueueBatchCount: number | bigint;
};

/** Gets the encoder for {@link UpdateAppliedEventArgs} event data. */
export function getUpdateAppliedEventEncoder(): FixedSizeEncoder<UpdateAppliedEventArgs> {
    return getHiddenPrefixEncoder(
        getStructEncoder([
            ['outputSlot', getU64Encoder()],
            ['queueCursor', getU64Encoder()],
            ['verifiedStateRoot', fixEncoderSize(getBytesEncoder(), 32)],
            ['proofQueueBatchCount', getU64Encoder()],
        ]),
        [getConstantEncoder(UPDATE_APPLIED_EVENT_DISCRIMINATOR)]
    );
}

/** Gets the decoder for {@link UpdateAppliedEvent} event data. */
export function getUpdateAppliedEventDecoder(): FixedSizeDecoder<UpdateAppliedEvent> {
    return getHiddenPrefixDecoder(
        getStructDecoder([
            ['outputSlot', getU64Decoder()],
            ['queueCursor', getU64Decoder()],
            ['verifiedStateRoot', fixDecoderSize(getBytesDecoder(), 32)],
            ['proofQueueBatchCount', getU64Decoder()],
        ]),
        [getConstantDecoder(UPDATE_APPLIED_EVENT_DISCRIMINATOR)]
    );
}

/** Gets the codec for {@link UpdateAppliedEvent} event data. */
export function getUpdateAppliedEventCodec(): FixedSizeCodec<
    UpdateAppliedEventArgs,
    UpdateAppliedEvent
> {
    return combineCodec(
        getUpdateAppliedEventEncoder(),
        getUpdateAppliedEventDecoder()
    );
}

/** Parses the provided bytes into {@link UpdateAppliedEvent} event data. */
export function parseUpdateAppliedEvent(
    data: ReadonlyUint8Array | Uint8Array
): UpdateAppliedEvent {
    if (containsBytes(data, UPDATE_APPLIED_EVENT_DISCRIMINATOR, 0)) {
        return getUpdateAppliedEventDecoder().decode(data);
    }
    throw new Error(
        'The provided data does not match the "UpdateAppliedEvent" event discriminators.'
    );
}
