/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace NoriProofRequestQueue {
      
    export type RequestStruct = {target: AddressLike, slotKey: BytesLike, collectionKeysCount: BigNumberish, collectionKeys: [BytesLike, BytesLike]}

    export type RequestStructOutput = [target: string, slotKey: string, collectionKeysCount: bigint, collectionKeys: [string, string]] & {target: string, slotKey: string, collectionKeysCount: bigint, collectionKeys: [string, string] }
  
    }

  export interface NoriProofRequestQueueInterface extends Interface {
    getFunction(nameOrSignature: "MAX_COLLECTION_KEYS" | "MAX_PROOF_REQUEST_QUEUE_FEE" | "PROOF_REQUEST_QUEUE_FEE_GRANULARITY_WEI" | "accumulatedFees" | "feeRecipient" | "head" | "operator" | "proofRequestQueueFee" | "requestProof" | "requests" | "setFeeRecipient" | "setOperator" | "setProofRequestQueueFee" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeeRecipientSet" | "FeesWithdrawn" | "OperatorSet" | "ProofRequestQueueFeeSet" | "ProofRequested"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_COLLECTION_KEYS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_PROOF_REQUEST_QUEUE_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PROOF_REQUEST_QUEUE_FEE_GRANULARITY_WEI', values?: undefined): string;
encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'head', values?: undefined): string;
encodeFunctionData(functionFragment: 'operator', values?: undefined): string;
encodeFunctionData(functionFragment: 'proofRequestQueueFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestProof', values: [BytesLike, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'requests', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setFeeRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setOperator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setProofRequestQueueFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_COLLECTION_KEYS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_PROOF_REQUEST_QUEUE_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PROOF_REQUEST_QUEUE_FEE_GRANULARITY_WEI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'head', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofRequestQueueFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProofRequestQueueFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace FeeRecipientSetEvent {
      export type InputTuple = [oldRecipient: AddressLike, newRecipient: AddressLike];
      export type OutputTuple = [oldRecipient: string, newRecipient: string];
      export interface OutputObject {oldRecipient: string, newRecipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [recipient: string, amount: bigint];
      export interface OutputObject {recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OperatorSetEvent {
      export type InputTuple = [oldOperator: AddressLike, newOperator: AddressLike];
      export type OutputTuple = [oldOperator: string, newOperator: string];
      export interface OutputObject {oldOperator: string, newOperator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProofRequestQueueFeeSetEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProofRequestedEvent {
      export type InputTuple = [requestId: BigNumberish, target: AddressLike, slotKey: BytesLike, collectionKeys: BytesLike[]];
      export type OutputTuple = [requestId: bigint, target: string, slotKey: string, collectionKeys: string[]];
      export interface OutputObject {requestId: bigint, target: string, slotKey: string, collectionKeys: string[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoriProofRequestQueue extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoriProofRequestQueue;
    waitForDeployment(): Promise<this>;

    interface: NoriProofRequestQueueInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_COLLECTION_KEYS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_PROOF_REQUEST_QUEUE_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PROOF_REQUEST_QUEUE_FEE_GRANULARITY_WEI: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    accumulatedFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    head: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    operator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proofRequestQueueFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    requestProof: TypedContractMethod<
      [slotKey: BytesLike, collectionKeys: BytesLike[], ],
      [bigint],
      'payable'
    >
    

    
    requests: TypedContractMethod<
      [requestId: BigNumberish, ],
      [NoriProofRequestQueue.RequestStructOutput],
      'view'
    >
    

    
    setFeeRecipient: TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setOperator: TypedContractMethod<
      [newOperator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setProofRequestQueueFee: TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_COLLECTION_KEYS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_PROOF_REQUEST_QUEUE_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PROOF_REQUEST_QUEUE_FEE_GRANULARITY_WEI'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'head'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'operator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proofRequestQueueFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'requestProof'): TypedContractMethod<
      [slotKey: BytesLike, collectionKeys: BytesLike[], ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'requests'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [NoriProofRequestQueue.RequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'setFeeRecipient'): TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOperator'): TypedContractMethod<
      [newOperator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProofRequestQueueFee'): TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FeeRecipientSet'): TypedContractEvent<FeeRecipientSetEvent.InputTuple, FeeRecipientSetEvent.OutputTuple, FeeRecipientSetEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'OperatorSet'): TypedContractEvent<OperatorSetEvent.InputTuple, OperatorSetEvent.OutputTuple, OperatorSetEvent.OutputObject>;
getEvent(key: 'ProofRequestQueueFeeSet'): TypedContractEvent<ProofRequestQueueFeeSetEvent.InputTuple, ProofRequestQueueFeeSetEvent.OutputTuple, ProofRequestQueueFeeSetEvent.OutputObject>;
getEvent(key: 'ProofRequested'): TypedContractEvent<ProofRequestedEvent.InputTuple, ProofRequestedEvent.OutputTuple, ProofRequestedEvent.OutputObject>;

    filters: {
      
      'FeeRecipientSet(address,address)': TypedContractEvent<FeeRecipientSetEvent.InputTuple, FeeRecipientSetEvent.OutputTuple, FeeRecipientSetEvent.OutputObject>;
      FeeRecipientSet: TypedContractEvent<FeeRecipientSetEvent.InputTuple, FeeRecipientSetEvent.OutputTuple, FeeRecipientSetEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'OperatorSet(address,address)': TypedContractEvent<OperatorSetEvent.InputTuple, OperatorSetEvent.OutputTuple, OperatorSetEvent.OutputObject>;
      OperatorSet: TypedContractEvent<OperatorSetEvent.InputTuple, OperatorSetEvent.OutputTuple, OperatorSetEvent.OutputObject>;
    

      'ProofRequestQueueFeeSet(uint256,uint256)': TypedContractEvent<ProofRequestQueueFeeSetEvent.InputTuple, ProofRequestQueueFeeSetEvent.OutputTuple, ProofRequestQueueFeeSetEvent.OutputObject>;
      ProofRequestQueueFeeSet: TypedContractEvent<ProofRequestQueueFeeSetEvent.InputTuple, ProofRequestQueueFeeSetEvent.OutputTuple, ProofRequestQueueFeeSetEvent.OutputObject>;
    

      'ProofRequested(uint256,address,bytes32,bytes32[])': TypedContractEvent<ProofRequestedEvent.InputTuple, ProofRequestedEvent.OutputTuple, ProofRequestedEvent.OutputObject>;
      ProofRequested: TypedContractEvent<ProofRequestedEvent.InputTuple, ProofRequestedEvent.OutputTuple, ProofRequestedEvent.OutputObject>;
    
    };
  }