/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    combineCodec,
    fixDecoderSize,
    fixEncoderSize,
    getBytesDecoder,
    getBytesEncoder,
    getStructDecoder,
    getStructEncoder,
    getU64Decoder,
    getU64Encoder,
    SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
    SolanaError,
    transformEncoder,
    type AccountMeta,
    type AccountSignerMeta,
    type Address,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type Instruction,
    type InstructionWithAccounts,
    type InstructionWithData,
    type ReadonlyAccount,
    type ReadonlyUint8Array,
    type WritableAccount,
    type WritableSignerAccount,
} from '@solana/kit';
import {
    getAccountMetaFactory,
    type InstructionAccountInput,
    type InstructionAccountInputAddress,
    type InstructionSignerInput,
    type ResolvedInstructionAccount,
    type ResolvedInstructionAccountMeta,
} from '@solana/program-client-core';
import { findStatePda, findTokenPda } from '../pdas/index.js';
import { TOKEN_PROGRAM_ADDRESS } from '../programs/index.js';
import {
    getBytes32Decoder,
    getBytes32Encoder,
    getEthAddressDecoder,
    getEthAddressEncoder,
    type Bytes32,
    type Bytes32Args,
    type EthAddress,
    type EthAddressArgs,
} from '../types/index.js';

export const INITIALIZE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
    175, 175, 109, 31, 13, 152, 155, 237,
]);

export function getInitializeDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(
        INITIALIZE_DISCRIMINATOR
    );
}

export type InitializeInstruction<
    TProgram extends string = typeof TOKEN_PROGRAM_ADDRESS,
    TAccountPayer extends string | AccountMeta<string> = string,
    TAccountState extends string | AccountMeta<string> = string,
    TAccountToken extends string | AccountMeta<string> = string,
    TAccountSystemProgram extends string | AccountMeta<string> =
        '11111111111111111111111111111111',
    TAccountTokenProgram extends string | AccountMeta<string> =
        'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
    InstructionWithData<ReadonlyUint8Array> &
    InstructionWithAccounts<
        [
            TAccountPayer extends string
                ? WritableSignerAccount<TAccountPayer> &
                      AccountSignerMeta<TAccountPayer>
                : TAccountPayer,
            TAccountState extends string
                ? WritableAccount<TAccountState>
                : TAccountState,
            TAccountToken extends string
                ? WritableAccount<TAccountToken>
                : TAccountToken,
            TAccountSystemProgram extends string
                ? ReadonlyAccount<TAccountSystemProgram>
                : TAccountSystemProgram,
            TAccountTokenProgram extends string
                ? ReadonlyAccount<TAccountTokenProgram>
                : TAccountTokenProgram,
            ...TRemainingAccounts,
        ]
    >;

export type InitializeInstructionData = {
    discriminator: ReadonlyUint8Array;
    verifiedStateRoot: Bytes32;
    latestHeliosStoreInputHash: Bytes32;
    ethProofQueueAddress: EthAddress;
    ethTokenBridgeAddress: EthAddress;
    /**
     * Beacon slot of the state the bridge starts from. The first accepted
     * `update` must have `input_slot == latest_head`, so this pins where the
     * proven chain resumes.
     */
    latestHead: bigint;
    queueCursor: bigint;
};

export type InitializeInstructionDataArgs = {
    verifiedStateRoot: Bytes32Args;
    latestHeliosStoreInputHash: Bytes32Args;
    ethProofQueueAddress: EthAddressArgs;
    ethTokenBridgeAddress: EthAddressArgs;
    /**
     * Beacon slot of the state the bridge starts from. The first accepted
     * `update` must have `input_slot == latest_head`, so this pins where the
     * proven chain resumes.
     */
    latestHead: number | bigint;
    queueCursor: number | bigint;
};

export function getInitializeInstructionDataEncoder(): FixedSizeEncoder<InitializeInstructionDataArgs> {
    return transformEncoder(
        getStructEncoder([
            ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
            ['verifiedStateRoot', getBytes32Encoder()],
            ['latestHeliosStoreInputHash', getBytes32Encoder()],
            ['ethProofQueueAddress', getEthAddressEncoder()],
            ['ethTokenBridgeAddress', getEthAddressEncoder()],
            ['latestHead', getU64Encoder()],
            ['queueCursor', getU64Encoder()],
        ]),
        (value) => ({ ...value, discriminator: INITIALIZE_DISCRIMINATOR })
    );
}

export function getInitializeInstructionDataDecoder(): FixedSizeDecoder<InitializeInstructionData> {
    return getStructDecoder([
        ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
        ['verifiedStateRoot', getBytes32Decoder()],
        ['latestHeliosStoreInputHash', getBytes32Decoder()],
        ['ethProofQueueAddress', getEthAddressDecoder()],
        ['ethTokenBridgeAddress', getEthAddressDecoder()],
        ['latestHead', getU64Decoder()],
        ['queueCursor', getU64Decoder()],
    ]);
}

export function getInitializeInstructionDataCodec(): FixedSizeCodec<
    InitializeInstructionDataArgs,
    InitializeInstructionData
> {
    return combineCodec(
        getInitializeInstructionDataEncoder(),
        getInitializeInstructionDataDecoder()
    );
}

export type InitializeAsyncInput<
    TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
    TAccountState extends InstructionAccountInput = InstructionAccountInput,
    TAccountToken extends InstructionAccountInput = InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountTokenProgram extends InstructionAccountInput =
        InstructionAccountInput,
> = {
    payer: TAccountPayer;
    state?: TAccountState;
    token?: TAccountToken;
    systemProgram?: TAccountSystemProgram;
    tokenProgram?: TAccountTokenProgram;
    verifiedStateRoot: InitializeInstructionDataArgs['verifiedStateRoot'];
    latestHeliosStoreInputHash: InitializeInstructionDataArgs['latestHeliosStoreInputHash'];
    ethProofQueueAddress: InitializeInstructionDataArgs['ethProofQueueAddress'];
    ethTokenBridgeAddress: InitializeInstructionDataArgs['ethTokenBridgeAddress'];
    latestHead: InitializeInstructionDataArgs['latestHead'];
    queueCursor: InitializeInstructionDataArgs['queueCursor'];
};

export async function getInitializeInstructionAsync<
    TAccountPayer extends InstructionSignerInput,
    TAccountState extends InstructionAccountInput,
    TAccountToken extends InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput,
    TAccountTokenProgram extends InstructionAccountInput,
    TProgramAddress extends Address = typeof TOKEN_PROGRAM_ADDRESS,
>(
    input: InitializeAsyncInput<
        TAccountPayer,
        TAccountState,
        TAccountToken,
        TAccountSystemProgram,
        TAccountTokenProgram
    >,
    config?: { programAddress?: TProgramAddress }
): Promise<
    InitializeInstruction<
        TProgramAddress,
        ResolvedInstructionAccountMeta<
            TAccountPayer,
            InstructionAccountInputAddress<TAccountPayer>
        >,
        ResolvedInstructionAccountMeta<
            TAccountState,
            InstructionAccountInputAddress<TAccountState>
        >,
        ResolvedInstructionAccountMeta<
            TAccountToken,
            InstructionAccountInputAddress<TAccountToken>
        >,
        ResolvedInstructionAccountMeta<
            TAccountSystemProgram,
            InstructionAccountInputAddress<TAccountSystemProgram>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenProgram,
            InstructionAccountInputAddress<TAccountTokenProgram>
        >
    >
> {
    // Program address.
    const programAddress = config?.programAddress ?? TOKEN_PROGRAM_ADDRESS;

    // Account meta helper.
    const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

    // Original accounts.
    const originalAccounts = {
        payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
        state: {
            value: input.state ?? null,
            isSigner: false,
            isWritable: true,
        },
        token: {
            value: input.token ?? null,
            isSigner: false,
            isWritable: true,
        },
        systemProgram: {
            value: input.systemProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
        tokenProgram: {
            value: input.tokenProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
    };
    const accounts = originalAccounts as Record<
        keyof typeof originalAccounts,
        ResolvedInstructionAccount
    >;

    // Original args.
    const args = { ...input };

    // Resolve default values.
    if (!accounts.state.value) {
        accounts.state.value = await findStatePda({ programAddress });
    }
    if (!accounts.token.value) {
        accounts.token.value = await findTokenPda({ programAddress });
    }
    if (!accounts.systemProgram.value) {
        accounts.systemProgram.value =
            '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
    }
    if (!accounts.tokenProgram.value) {
        accounts.tokenProgram.value =
            'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
    }

    return Object.freeze({
        accounts: [
            getAccountMeta('payer', accounts.payer),
            getAccountMeta('state', accounts.state),
            getAccountMeta('token', accounts.token),
            getAccountMeta('systemProgram', accounts.systemProgram),
            getAccountMeta('tokenProgram', accounts.tokenProgram),
        ],
        data: getInitializeInstructionDataEncoder().encode(
            args as InitializeInstructionDataArgs
        ),
        programAddress,
    } as InitializeInstruction<
        TProgramAddress,
        ResolvedInstructionAccountMeta<
            TAccountPayer,
            InstructionAccountInputAddress<TAccountPayer>
        >,
        ResolvedInstructionAccountMeta<
            TAccountState,
            InstructionAccountInputAddress<TAccountState>
        >,
        ResolvedInstructionAccountMeta<
            TAccountToken,
            InstructionAccountInputAddress<TAccountToken>
        >,
        ResolvedInstructionAccountMeta<
            TAccountSystemProgram,
            InstructionAccountInputAddress<TAccountSystemProgram>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenProgram,
            InstructionAccountInputAddress<TAccountTokenProgram>
        >
    >);
}

export type InitializeInput<
    TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
    TAccountState extends InstructionAccountInput = InstructionAccountInput,
    TAccountToken extends InstructionAccountInput = InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountTokenProgram extends InstructionAccountInput =
        InstructionAccountInput,
> = {
    payer: TAccountPayer;
    state: TAccountState;
    token: TAccountToken;
    systemProgram?: TAccountSystemProgram;
    tokenProgram?: TAccountTokenProgram;
    verifiedStateRoot: InitializeInstructionDataArgs['verifiedStateRoot'];
    latestHeliosStoreInputHash: InitializeInstructionDataArgs['latestHeliosStoreInputHash'];
    ethProofQueueAddress: InitializeInstructionDataArgs['ethProofQueueAddress'];
    ethTokenBridgeAddress: InitializeInstructionDataArgs['ethTokenBridgeAddress'];
    latestHead: InitializeInstructionDataArgs['latestHead'];
    queueCursor: InitializeInstructionDataArgs['queueCursor'];
};

export function getInitializeInstruction<
    TAccountPayer extends InstructionSignerInput,
    TAccountState extends InstructionAccountInput,
    TAccountToken extends InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput,
    TAccountTokenProgram extends InstructionAccountInput,
    TProgramAddress extends Address = typeof TOKEN_PROGRAM_ADDRESS,
>(
    input: InitializeInput<
        TAccountPayer,
        TAccountState,
        TAccountToken,
        TAccountSystemProgram,
        TAccountTokenProgram
    >,
    config?: { programAddress?: TProgramAddress }
): InitializeInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
        TAccountPayer,
        InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
        TAccountState,
        InstructionAccountInputAddress<TAccountState>
    >,
    ResolvedInstructionAccountMeta<
        TAccountToken,
        InstructionAccountInputAddress<TAccountToken>
    >,
    ResolvedInstructionAccountMeta<
        TAccountSystemProgram,
        InstructionAccountInputAddress<TAccountSystemProgram>
    >,
    ResolvedInstructionAccountMeta<
        TAccountTokenProgram,
        InstructionAccountInputAddress<TAccountTokenProgram>
    >
> {
    // Program address.
    const programAddress = config?.programAddress ?? TOKEN_PROGRAM_ADDRESS;

    // Account meta helper.
    const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

    // Original accounts.
    const originalAccounts = {
        payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
        state: {
            value: input.state ?? null,
            isSigner: false,
            isWritable: true,
        },
        token: {
            value: input.token ?? null,
            isSigner: false,
            isWritable: true,
        },
        systemProgram: {
            value: input.systemProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
        tokenProgram: {
            value: input.tokenProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
    };
    const accounts = originalAccounts as Record<
        keyof typeof originalAccounts,
        ResolvedInstructionAccount
    >;

    // Original args.
    const args = { ...input };

    // Resolve default values.
    if (!accounts.systemProgram.value) {
        accounts.systemProgram.value =
            '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
    }
    if (!accounts.tokenProgram.value) {
        accounts.tokenProgram.value =
            'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
    }

    return Object.freeze({
        accounts: [
            getAccountMeta('payer', accounts.payer),
            getAccountMeta('state', accounts.state),
            getAccountMeta('token', accounts.token),
            getAccountMeta('systemProgram', accounts.systemProgram),
            getAccountMeta('tokenProgram', accounts.tokenProgram),
        ],
        data: getInitializeInstructionDataEncoder().encode(
            args as InitializeInstructionDataArgs
        ),
        programAddress,
    } as InitializeInstruction<
        TProgramAddress,
        ResolvedInstructionAccountMeta<
            TAccountPayer,
            InstructionAccountInputAddress<TAccountPayer>
        >,
        ResolvedInstructionAccountMeta<
            TAccountState,
            InstructionAccountInputAddress<TAccountState>
        >,
        ResolvedInstructionAccountMeta<
            TAccountToken,
            InstructionAccountInputAddress<TAccountToken>
        >,
        ResolvedInstructionAccountMeta<
            TAccountSystemProgram,
            InstructionAccountInputAddress<TAccountSystemProgram>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenProgram,
            InstructionAccountInputAddress<TAccountTokenProgram>
        >
    >);
}

export type ParsedInitializeInstruction<
    TProgram extends string = typeof TOKEN_PROGRAM_ADDRESS,
    TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
    programAddress: Address<TProgram>;
    accounts: {
        payer: TAccountMetas[0];
        state: TAccountMetas[1];
        token: TAccountMetas[2];
        systemProgram: TAccountMetas[3];
        tokenProgram: TAccountMetas[4];
    };
    data: InitializeInstructionData;
};

export function parseInitializeInstruction<
    TProgram extends string,
    TAccountMetas extends readonly AccountMeta[],
>(
    instruction: Instruction<TProgram> &
        InstructionWithAccounts<TAccountMetas> &
        InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeInstruction<TProgram, TAccountMetas> {
    if (instruction.accounts.length < 5) {
        throw new SolanaError(
            SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
            {
                actualAccountMetas: instruction.accounts.length,
                expectedAccountMetas: 5,
            }
        );
    }
    let accountIndex = 0;
    const getNextAccount = () => {
        const accountMeta = (instruction.accounts as TAccountMetas)[
            accountIndex
        ]!;
        accountIndex += 1;
        return accountMeta;
    };
    return {
        programAddress: instruction.programAddress,
        accounts: {
            payer: getNextAccount(),
            state: getNextAccount(),
            token: getNextAccount(),
            systemProgram: getNextAccount(),
            tokenProgram: getNextAccount(),
        },
        data: getInitializeInstructionDataDecoder().decode(instruction.data),
    };
}
