/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    combineCodec,
    fixDecoderSize,
    fixEncoderSize,
    getArrayDecoder,
    getArrayEncoder,
    getBytesDecoder,
    getBytesEncoder,
    getStructDecoder,
    getStructEncoder,
    getU64Decoder,
    getU64Encoder,
    SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
    SolanaError,
    transformEncoder,
    type AccountMeta,
    type AccountSignerMeta,
    type Address,
    type Codec,
    type Decoder,
    type Encoder,
    type Instruction,
    type InstructionWithAccounts,
    type InstructionWithData,
    type ReadonlyAccount,
    type ReadonlyUint8Array,
    type WritableAccount,
    type WritableSignerAccount,
} from '@solana/kit';
import {
    getAccountMetaFactory,
    getAddressFromResolvedInstructionAccount,
    type InstructionAccountInput,
    type InstructionAccountInputAddress,
    type InstructionSignerInput,
    type ResolvedInstructionAccount,
    type ResolvedInstructionAccountMeta,
} from '@solana/program-client-core';
import {
    findStatePda,
    findTokenAccountStoragePda,
    findTokenPda,
} from '../pdas/index.js';
import { TOKEN_PROGRAM_ADDRESS } from '../programs/index.js';
import {
    getBytes32Decoder,
    getBytes32Encoder,
    getVerifiedRequestDecoder,
    getVerifiedRequestEncoder,
    type Bytes32,
    type Bytes32Args,
    type VerifiedRequest,
    type VerifiedRequestArgs,
} from '../types/index.js';

export const MINT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
    51, 57, 225, 47, 182, 146, 137, 166,
]);

export function getMintDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(MINT_DISCRIMINATOR);
}

export type MintInstruction<
    TProgram extends string = typeof TOKEN_PROGRAM_ADDRESS,
    TAccountPayer extends string | AccountMeta<string> = string,
    TAccountRecipient extends string | AccountMeta<string> = string,
    TAccountState extends string | AccountMeta<string> = string,
    TAccountToken extends string | AccountMeta<string> = string,
    TAccountTokenAccount extends string | AccountMeta<string> = string,
    TAccountTokenAccountStorage extends string | AccountMeta<string> = string,
    TAccountProofQueueBatch extends string | AccountMeta<string> = string,
    TAccountSystemProgram extends string | AccountMeta<string> =
        '11111111111111111111111111111111',
    TAccountTokenProgram extends string | AccountMeta<string> =
        'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
    TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
    InstructionWithData<ReadonlyUint8Array> &
    InstructionWithAccounts<
        [
            TAccountPayer extends string
                ? WritableSignerAccount<TAccountPayer> &
                      AccountSignerMeta<TAccountPayer>
                : TAccountPayer,
            TAccountRecipient extends string
                ? WritableSignerAccount<TAccountRecipient> &
                      AccountSignerMeta<TAccountRecipient>
                : TAccountRecipient,
            TAccountState extends string
                ? ReadonlyAccount<TAccountState>
                : TAccountState,
            TAccountToken extends string
                ? WritableAccount<TAccountToken>
                : TAccountToken,
            TAccountTokenAccount extends string
                ? WritableAccount<TAccountTokenAccount>
                : TAccountTokenAccount,
            TAccountTokenAccountStorage extends string
                ? WritableAccount<TAccountTokenAccountStorage>
                : TAccountTokenAccountStorage,
            TAccountProofQueueBatch extends string
                ? ReadonlyAccount<TAccountProofQueueBatch>
                : TAccountProofQueueBatch,
            TAccountSystemProgram extends string
                ? ReadonlyAccount<TAccountSystemProgram>
                : TAccountSystemProgram,
            TAccountTokenProgram extends string
                ? ReadonlyAccount<TAccountTokenProgram>
                : TAccountTokenProgram,
            TAccountAssociatedTokenProgram extends string
                ? ReadonlyAccount<TAccountAssociatedTokenProgram>
                : TAccountAssociatedTokenProgram,
            ...TRemainingAccounts,
        ]
    >;

export type MintInstructionData = {
    discriminator: ReadonlyUint8Array;
    path: Array<Bytes32>;
    index: bigint;
    value: VerifiedRequest;
};

export type MintInstructionDataArgs = {
    path: Array<Bytes32Args>;
    index: number | bigint;
    value: VerifiedRequestArgs;
};

export function getMintInstructionDataEncoder(): Encoder<MintInstructionDataArgs> {
    return transformEncoder(
        getStructEncoder([
            ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
            ['path', getArrayEncoder(getBytes32Encoder())],
            ['index', getU64Encoder()],
            ['value', getVerifiedRequestEncoder()],
        ]),
        (value) => ({ ...value, discriminator: MINT_DISCRIMINATOR })
    );
}

export function getMintInstructionDataDecoder(): Decoder<MintInstructionData> {
    return getStructDecoder([
        ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
        ['path', getArrayDecoder(getBytes32Decoder())],
        ['index', getU64Decoder()],
        ['value', getVerifiedRequestDecoder()],
    ]);
}

export function getMintInstructionDataCodec(): Codec<
    MintInstructionDataArgs,
    MintInstructionData
> {
    return combineCodec(
        getMintInstructionDataEncoder(),
        getMintInstructionDataDecoder()
    );
}

export type MintAsyncInput<
    TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
    TAccountRecipient extends InstructionSignerInput = InstructionSignerInput,
    TAccountState extends InstructionAccountInput = InstructionAccountInput,
    TAccountToken extends InstructionAccountInput = InstructionAccountInput,
    TAccountTokenAccount extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountTokenAccountStorage extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountProofQueueBatch extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountTokenProgram extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountAssociatedTokenProgram extends InstructionAccountInput =
        InstructionAccountInput,
> = {
    payer: TAccountPayer;
    recipient: TAccountRecipient;
    state?: TAccountState;
    token?: TAccountToken;
    /**
     * create_idempotent CPI below, which derives the ATA address itself and
     * verifies any pre-existing account at it is a valid token account for
     * this mint/owner/token_program.
     */
    tokenAccount: TAccountTokenAccount;
    /**
     * created and initialized in handle_mint on first use (not via Anchor's
     * init_if_needed, which would skip re-running our init logic on an
     * account an attacker got created ahead of time) and left untouched if
     * it already exists.
     */
    tokenAccountStorage?: TAccountTokenAccountStorage;
    /**
     * The committed proof queue batch the deposit witness proves against.
     * `Account` checks it is owned by this program and carries the
     * `ProofRequestRootEntry` discriminator; only `update` creates such
     * accounts, at the proof queue batch PDAs.
     */
    proofQueueBatch: TAccountProofQueueBatch;
    systemProgram?: TAccountSystemProgram;
    tokenProgram?: TAccountTokenProgram;
    associatedTokenProgram?: TAccountAssociatedTokenProgram;
    path: MintInstructionDataArgs['path'];
    index: MintInstructionDataArgs['index'];
    value: MintInstructionDataArgs['value'];
};

export async function getMintInstructionAsync<
    TAccountPayer extends InstructionSignerInput,
    TAccountRecipient extends InstructionSignerInput,
    TAccountState extends InstructionAccountInput,
    TAccountToken extends InstructionAccountInput,
    TAccountTokenAccount extends InstructionAccountInput,
    TAccountTokenAccountStorage extends InstructionAccountInput,
    TAccountProofQueueBatch extends InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput,
    TAccountTokenProgram extends InstructionAccountInput,
    TAccountAssociatedTokenProgram extends InstructionAccountInput,
    TProgramAddress extends Address = typeof TOKEN_PROGRAM_ADDRESS,
>(
    input: MintAsyncInput<
        TAccountPayer,
        TAccountRecipient,
        TAccountState,
        TAccountToken,
        TAccountTokenAccount,
        TAccountTokenAccountStorage,
        TAccountProofQueueBatch,
        TAccountSystemProgram,
        TAccountTokenProgram,
        TAccountAssociatedTokenProgram
    >,
    config?: { programAddress?: TProgramAddress }
): Promise<
    MintInstruction<
        TProgramAddress,
        ResolvedInstructionAccountMeta<
            TAccountPayer,
            InstructionAccountInputAddress<TAccountPayer>
        >,
        ResolvedInstructionAccountMeta<
            TAccountRecipient,
            InstructionAccountInputAddress<TAccountRecipient>
        >,
        ResolvedInstructionAccountMeta<
            TAccountState,
            InstructionAccountInputAddress<TAccountState>
        >,
        ResolvedInstructionAccountMeta<
            TAccountToken,
            InstructionAccountInputAddress<TAccountToken>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenAccount,
            InstructionAccountInputAddress<TAccountTokenAccount>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenAccountStorage,
            InstructionAccountInputAddress<TAccountTokenAccountStorage>
        >,
        ResolvedInstructionAccountMeta<
            TAccountProofQueueBatch,
            InstructionAccountInputAddress<TAccountProofQueueBatch>
        >,
        ResolvedInstructionAccountMeta<
            TAccountSystemProgram,
            InstructionAccountInputAddress<TAccountSystemProgram>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenProgram,
            InstructionAccountInputAddress<TAccountTokenProgram>
        >,
        ResolvedInstructionAccountMeta<
            TAccountAssociatedTokenProgram,
            InstructionAccountInputAddress<TAccountAssociatedTokenProgram>
        >
    >
> {
    // Program address.
    const programAddress = config?.programAddress ?? TOKEN_PROGRAM_ADDRESS;

    // Account meta helper.
    const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

    // Original accounts.
    const originalAccounts = {
        payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
        recipient: {
            value: input.recipient ?? null,
            isSigner: true,
            isWritable: true,
        },
        state: {
            value: input.state ?? null,
            isSigner: false,
            isWritable: false,
        },
        token: {
            value: input.token ?? null,
            isSigner: false,
            isWritable: true,
        },
        tokenAccount: {
            value: input.tokenAccount ?? null,
            isSigner: false,
            isWritable: true,
        },
        tokenAccountStorage: {
            value: input.tokenAccountStorage ?? null,
            isSigner: false,
            isWritable: true,
        },
        proofQueueBatch: {
            value: input.proofQueueBatch ?? null,
            isSigner: false,
            isWritable: false,
        },
        systemProgram: {
            value: input.systemProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
        tokenProgram: {
            value: input.tokenProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
        associatedTokenProgram: {
            value: input.associatedTokenProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
    };
    const accounts = originalAccounts as Record<
        keyof typeof originalAccounts,
        ResolvedInstructionAccount
    >;

    // Original args.
    const args = { ...input };

    // Resolve default values.
    if (!accounts.state.value) {
        accounts.state.value = await findStatePda({ programAddress });
    }
    if (!accounts.token.value) {
        accounts.token.value = await findTokenPda({ programAddress });
    }
    if (!accounts.tokenAccountStorage.value) {
        accounts.tokenAccountStorage.value = await findTokenAccountStoragePda(
            {
                recipient: getAddressFromResolvedInstructionAccount(
                    'recipient',
                    accounts.recipient.value
                ),
            },
            { programAddress }
        );
    }
    if (!accounts.systemProgram.value) {
        accounts.systemProgram.value =
            '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
    }
    if (!accounts.tokenProgram.value) {
        accounts.tokenProgram.value =
            'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
    }
    if (!accounts.associatedTokenProgram.value) {
        accounts.associatedTokenProgram.value =
            'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
    }

    return Object.freeze({
        accounts: [
            getAccountMeta('payer', accounts.payer),
            getAccountMeta('recipient', accounts.recipient),
            getAccountMeta('state', accounts.state),
            getAccountMeta('token', accounts.token),
            getAccountMeta('tokenAccount', accounts.tokenAccount),
            getAccountMeta('tokenAccountStorage', accounts.tokenAccountStorage),
            getAccountMeta('proofQueueBatch', accounts.proofQueueBatch),
            getAccountMeta('systemProgram', accounts.systemProgram),
            getAccountMeta('tokenProgram', accounts.tokenProgram),
            getAccountMeta(
                'associatedTokenProgram',
                accounts.associatedTokenProgram
            ),
        ],
        data: getMintInstructionDataEncoder().encode(
            args as MintInstructionDataArgs
        ),
        programAddress,
    } as MintInstruction<
        TProgramAddress,
        ResolvedInstructionAccountMeta<
            TAccountPayer,
            InstructionAccountInputAddress<TAccountPayer>
        >,
        ResolvedInstructionAccountMeta<
            TAccountRecipient,
            InstructionAccountInputAddress<TAccountRecipient>
        >,
        ResolvedInstructionAccountMeta<
            TAccountState,
            InstructionAccountInputAddress<TAccountState>
        >,
        ResolvedInstructionAccountMeta<
            TAccountToken,
            InstructionAccountInputAddress<TAccountToken>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenAccount,
            InstructionAccountInputAddress<TAccountTokenAccount>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenAccountStorage,
            InstructionAccountInputAddress<TAccountTokenAccountStorage>
        >,
        ResolvedInstructionAccountMeta<
            TAccountProofQueueBatch,
            InstructionAccountInputAddress<TAccountProofQueueBatch>
        >,
        ResolvedInstructionAccountMeta<
            TAccountSystemProgram,
            InstructionAccountInputAddress<TAccountSystemProgram>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenProgram,
            InstructionAccountInputAddress<TAccountTokenProgram>
        >,
        ResolvedInstructionAccountMeta<
            TAccountAssociatedTokenProgram,
            InstructionAccountInputAddress<TAccountAssociatedTokenProgram>
        >
    >);
}

export type MintInput<
    TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
    TAccountRecipient extends InstructionSignerInput = InstructionSignerInput,
    TAccountState extends InstructionAccountInput = InstructionAccountInput,
    TAccountToken extends InstructionAccountInput = InstructionAccountInput,
    TAccountTokenAccount extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountTokenAccountStorage extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountProofQueueBatch extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountTokenProgram extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountAssociatedTokenProgram extends InstructionAccountInput =
        InstructionAccountInput,
> = {
    payer: TAccountPayer;
    recipient: TAccountRecipient;
    state: TAccountState;
    token: TAccountToken;
    /**
     * create_idempotent CPI below, which derives the ATA address itself and
     * verifies any pre-existing account at it is a valid token account for
     * this mint/owner/token_program.
     */
    tokenAccount: TAccountTokenAccount;
    /**
     * created and initialized in handle_mint on first use (not via Anchor's
     * init_if_needed, which would skip re-running our init logic on an
     * account an attacker got created ahead of time) and left untouched if
     * it already exists.
     */
    tokenAccountStorage: TAccountTokenAccountStorage;
    /**
     * The committed proof queue batch the deposit witness proves against.
     * `Account` checks it is owned by this program and carries the
     * `ProofRequestRootEntry` discriminator; only `update` creates such
     * accounts, at the proof queue batch PDAs.
     */
    proofQueueBatch: TAccountProofQueueBatch;
    systemProgram?: TAccountSystemProgram;
    tokenProgram?: TAccountTokenProgram;
    associatedTokenProgram?: TAccountAssociatedTokenProgram;
    path: MintInstructionDataArgs['path'];
    index: MintInstructionDataArgs['index'];
    value: MintInstructionDataArgs['value'];
};

export function getMintInstruction<
    TAccountPayer extends InstructionSignerInput,
    TAccountRecipient extends InstructionSignerInput,
    TAccountState extends InstructionAccountInput,
    TAccountToken extends InstructionAccountInput,
    TAccountTokenAccount extends InstructionAccountInput,
    TAccountTokenAccountStorage extends InstructionAccountInput,
    TAccountProofQueueBatch extends InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput,
    TAccountTokenProgram extends InstructionAccountInput,
    TAccountAssociatedTokenProgram extends InstructionAccountInput,
    TProgramAddress extends Address = typeof TOKEN_PROGRAM_ADDRESS,
>(
    input: MintInput<
        TAccountPayer,
        TAccountRecipient,
        TAccountState,
        TAccountToken,
        TAccountTokenAccount,
        TAccountTokenAccountStorage,
        TAccountProofQueueBatch,
        TAccountSystemProgram,
        TAccountTokenProgram,
        TAccountAssociatedTokenProgram
    >,
    config?: { programAddress?: TProgramAddress }
): MintInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
        TAccountPayer,
        InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
        TAccountRecipient,
        InstructionAccountInputAddress<TAccountRecipient>
    >,
    ResolvedInstructionAccountMeta<
        TAccountState,
        InstructionAccountInputAddress<TAccountState>
    >,
    ResolvedInstructionAccountMeta<
        TAccountToken,
        InstructionAccountInputAddress<TAccountToken>
    >,
    ResolvedInstructionAccountMeta<
        TAccountTokenAccount,
        InstructionAccountInputAddress<TAccountTokenAccount>
    >,
    ResolvedInstructionAccountMeta<
        TAccountTokenAccountStorage,
        InstructionAccountInputAddress<TAccountTokenAccountStorage>
    >,
    ResolvedInstructionAccountMeta<
        TAccountProofQueueBatch,
        InstructionAccountInputAddress<TAccountProofQueueBatch>
    >,
    ResolvedInstructionAccountMeta<
        TAccountSystemProgram,
        InstructionAccountInputAddress<TAccountSystemProgram>
    >,
    ResolvedInstructionAccountMeta<
        TAccountTokenProgram,
        InstructionAccountInputAddress<TAccountTokenProgram>
    >,
    ResolvedInstructionAccountMeta<
        TAccountAssociatedTokenProgram,
        InstructionAccountInputAddress<TAccountAssociatedTokenProgram>
    >
> {
    // Program address.
    const programAddress = config?.programAddress ?? TOKEN_PROGRAM_ADDRESS;

    // Account meta helper.
    const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

    // Original accounts.
    const originalAccounts = {
        payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
        recipient: {
            value: input.recipient ?? null,
            isSigner: true,
            isWritable: true,
        },
        state: {
            value: input.state ?? null,
            isSigner: false,
            isWritable: false,
        },
        token: {
            value: input.token ?? null,
            isSigner: false,
            isWritable: true,
        },
        tokenAccount: {
            value: input.tokenAccount ?? null,
            isSigner: false,
            isWritable: true,
        },
        tokenAccountStorage: {
            value: input.tokenAccountStorage ?? null,
            isSigner: false,
            isWritable: true,
        },
        proofQueueBatch: {
            value: input.proofQueueBatch ?? null,
            isSigner: false,
            isWritable: false,
        },
        systemProgram: {
            value: input.systemProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
        tokenProgram: {
            value: input.tokenProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
        associatedTokenProgram: {
            value: input.associatedTokenProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
    };
    const accounts = originalAccounts as Record<
        keyof typeof originalAccounts,
        ResolvedInstructionAccount
    >;

    // Original args.
    const args = { ...input };

    // Resolve default values.
    if (!accounts.systemProgram.value) {
        accounts.systemProgram.value =
            '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
    }
    if (!accounts.tokenProgram.value) {
        accounts.tokenProgram.value =
            'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
    }
    if (!accounts.associatedTokenProgram.value) {
        accounts.associatedTokenProgram.value =
            'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
    }

    return Object.freeze({
        accounts: [
            getAccountMeta('payer', accounts.payer),
            getAccountMeta('recipient', accounts.recipient),
            getAccountMeta('state', accounts.state),
            getAccountMeta('token', accounts.token),
            getAccountMeta('tokenAccount', accounts.tokenAccount),
            getAccountMeta('tokenAccountStorage', accounts.tokenAccountStorage),
            getAccountMeta('proofQueueBatch', accounts.proofQueueBatch),
            getAccountMeta('systemProgram', accounts.systemProgram),
            getAccountMeta('tokenProgram', accounts.tokenProgram),
            getAccountMeta(
                'associatedTokenProgram',
                accounts.associatedTokenProgram
            ),
        ],
        data: getMintInstructionDataEncoder().encode(
            args as MintInstructionDataArgs
        ),
        programAddress,
    } as MintInstruction<
        TProgramAddress,
        ResolvedInstructionAccountMeta<
            TAccountPayer,
            InstructionAccountInputAddress<TAccountPayer>
        >,
        ResolvedInstructionAccountMeta<
            TAccountRecipient,
            InstructionAccountInputAddress<TAccountRecipient>
        >,
        ResolvedInstructionAccountMeta<
            TAccountState,
            InstructionAccountInputAddress<TAccountState>
        >,
        ResolvedInstructionAccountMeta<
            TAccountToken,
            InstructionAccountInputAddress<TAccountToken>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenAccount,
            InstructionAccountInputAddress<TAccountTokenAccount>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenAccountStorage,
            InstructionAccountInputAddress<TAccountTokenAccountStorage>
        >,
        ResolvedInstructionAccountMeta<
            TAccountProofQueueBatch,
            InstructionAccountInputAddress<TAccountProofQueueBatch>
        >,
        ResolvedInstructionAccountMeta<
            TAccountSystemProgram,
            InstructionAccountInputAddress<TAccountSystemProgram>
        >,
        ResolvedInstructionAccountMeta<
            TAccountTokenProgram,
            InstructionAccountInputAddress<TAccountTokenProgram>
        >,
        ResolvedInstructionAccountMeta<
            TAccountAssociatedTokenProgram,
            InstructionAccountInputAddress<TAccountAssociatedTokenProgram>
        >
    >);
}

export type ParsedMintInstruction<
    TProgram extends string = typeof TOKEN_PROGRAM_ADDRESS,
    TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
    programAddress: Address<TProgram>;
    accounts: {
        payer: TAccountMetas[0];
        recipient: TAccountMetas[1];
        state: TAccountMetas[2];
        token: TAccountMetas[3];
        /**
         * create_idempotent CPI below, which derives the ATA address itself and
         * verifies any pre-existing account at it is a valid token account for
         * this mint/owner/token_program.
         */
        tokenAccount: TAccountMetas[4];
        /**
         * created and initialized in handle_mint on first use (not via Anchor's
         * init_if_needed, which would skip re-running our init logic on an
         * account an attacker got created ahead of time) and left untouched if
         * it already exists.
         */
        tokenAccountStorage: TAccountMetas[5];
        /**
         * The committed proof queue batch the deposit witness proves against.
         * `Account` checks it is owned by this program and carries the
         * `ProofRequestRootEntry` discriminator; only `update` creates such
         * accounts, at the proof queue batch PDAs.
         */
        proofQueueBatch: TAccountMetas[6];
        systemProgram: TAccountMetas[7];
        tokenProgram: TAccountMetas[8];
        associatedTokenProgram: TAccountMetas[9];
    };
    data: MintInstructionData;
};

export function parseMintInstruction<
    TProgram extends string,
    TAccountMetas extends readonly AccountMeta[],
>(
    instruction: Instruction<TProgram> &
        InstructionWithAccounts<TAccountMetas> &
        InstructionWithData<ReadonlyUint8Array>
): ParsedMintInstruction<TProgram, TAccountMetas> {
    if (instruction.accounts.length < 10) {
        throw new SolanaError(
            SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
            {
                actualAccountMetas: instruction.accounts.length,
                expectedAccountMetas: 10,
            }
        );
    }
    let accountIndex = 0;
    const getNextAccount = () => {
        const accountMeta = (instruction.accounts as TAccountMetas)[
            accountIndex
        ]!;
        accountIndex += 1;
        return accountMeta;
    };
    return {
        programAddress: instruction.programAddress,
        accounts: {
            payer: getNextAccount(),
            recipient: getNextAccount(),
            state: getNextAccount(),
            token: getNextAccount(),
            tokenAccount: getNextAccount(),
            tokenAccountStorage: getNextAccount(),
            proofQueueBatch: getNextAccount(),
            systemProgram: getNextAccount(),
            tokenProgram: getNextAccount(),
            associatedTokenProgram: getNextAccount(),
        },
        data: getMintInstructionDataDecoder().decode(instruction.data),
    };
}
