/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    addDecoderSizePrefix,
    addEncoderSizePrefix,
    combineCodec,
    fixDecoderSize,
    fixEncoderSize,
    getBytesDecoder,
    getBytesEncoder,
    getStructDecoder,
    getStructEncoder,
    getU32Decoder,
    getU32Encoder,
    SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
    SolanaError,
    transformEncoder,
    type AccountMeta,
    type AccountSignerMeta,
    type Address,
    type Codec,
    type Decoder,
    type Encoder,
    type Instruction,
    type InstructionWithAccounts,
    type InstructionWithData,
    type ReadonlyAccount,
    type ReadonlyUint8Array,
    type WritableAccount,
    type WritableSignerAccount,
} from '@solana/kit';
import {
    getAccountMetaFactory,
    type InstructionAccountInput,
    type InstructionAccountInputAddress,
    type InstructionSignerInput,
    type ResolvedInstructionAccount,
    type ResolvedInstructionAccountMeta,
} from '@solana/program-client-core';
import { findStatePda } from '../pdas/index.js';
import { TOKEN_PROGRAM_ADDRESS } from '../programs/index.js';

export const UPDATE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
    219, 200, 88, 176, 158, 63, 253, 127,
]);

export function getUpdateDiscriminatorBytes(): ReadonlyUint8Array {
    return fixEncoderSize(getBytesEncoder(), 8).encode(UPDATE_DISCRIMINATOR);
}

export type UpdateInstruction<
    TProgram extends string = typeof TOKEN_PROGRAM_ADDRESS,
    TAccountPayer extends string | AccountMeta<string> = string,
    TAccountState extends string | AccountMeta<string> = string,
    TAccountProofQueueBatch extends string | AccountMeta<string> = string,
    TAccountSystemProgram extends string | AccountMeta<string> =
        '11111111111111111111111111111111',
    TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
    InstructionWithData<ReadonlyUint8Array> &
    InstructionWithAccounts<
        [
            TAccountPayer extends string
                ? WritableSignerAccount<TAccountPayer> &
                      AccountSignerMeta<TAccountPayer>
                : TAccountPayer,
            TAccountState extends string
                ? WritableAccount<TAccountState>
                : TAccountState,
            TAccountProofQueueBatch extends string
                ? WritableAccount<TAccountProofQueueBatch>
                : TAccountProofQueueBatch,
            TAccountSystemProgram extends string
                ? ReadonlyAccount<TAccountSystemProgram>
                : TAccountSystemProgram,
            ...TRemainingAccounts,
        ]
    >;

export type UpdateInstructionData = {
    discriminator: ReadonlyUint8Array;
    proof: ReadonlyUint8Array;
    sp1PublicInputs: ReadonlyUint8Array;
};

export type UpdateInstructionDataArgs = {
    proof: ReadonlyUint8Array;
    sp1PublicInputs: ReadonlyUint8Array;
};

export function getUpdateInstructionDataEncoder(): Encoder<UpdateInstructionDataArgs> {
    return transformEncoder(
        getStructEncoder([
            ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
            ['proof', addEncoderSizePrefix(getBytesEncoder(), getU32Encoder())],
            [
                'sp1PublicInputs',
                addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
            ],
        ]),
        (value) => ({ ...value, discriminator: UPDATE_DISCRIMINATOR })
    );
}

export function getUpdateInstructionDataDecoder(): Decoder<UpdateInstructionData> {
    return getStructDecoder([
        ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
        ['proof', addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
        [
            'sp1PublicInputs',
            addDecoderSizePrefix(getBytesDecoder(), getU32Decoder()),
        ],
    ]);
}

export function getUpdateInstructionDataCodec(): Codec<
    UpdateInstructionDataArgs,
    UpdateInstructionData
> {
    return combineCodec(
        getUpdateInstructionDataEncoder(),
        getUpdateInstructionDataDecoder()
    );
}

export type UpdateAsyncInput<
    TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
    TAccountState extends InstructionAccountInput = InstructionAccountInput,
    TAccountProofQueueBatch extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput =
        InstructionAccountInput,
> = {
    payer: TAccountPayer;
    state?: TAccountState;
    /**
     * (`state.proof_queue_batch_count`). Its address can only be checked
     * against state inside the handler, so seeds are derived and compared
     * there; it is created and written in handle_update only when the
     * update's batch drained at least one request, and ignored otherwise.
     */
    proofQueueBatch: TAccountProofQueueBatch;
    systemProgram?: TAccountSystemProgram;
    proof: UpdateInstructionDataArgs['proof'];
    sp1PublicInputs: UpdateInstructionDataArgs['sp1PublicInputs'];
};

export async function getUpdateInstructionAsync<
    TAccountPayer extends InstructionSignerInput,
    TAccountState extends InstructionAccountInput,
    TAccountProofQueueBatch extends InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput,
    TProgramAddress extends Address = typeof TOKEN_PROGRAM_ADDRESS,
>(
    input: UpdateAsyncInput<
        TAccountPayer,
        TAccountState,
        TAccountProofQueueBatch,
        TAccountSystemProgram
    >,
    config?: { programAddress?: TProgramAddress }
): Promise<
    UpdateInstruction<
        TProgramAddress,
        ResolvedInstructionAccountMeta<
            TAccountPayer,
            InstructionAccountInputAddress<TAccountPayer>
        >,
        ResolvedInstructionAccountMeta<
            TAccountState,
            InstructionAccountInputAddress<TAccountState>
        >,
        ResolvedInstructionAccountMeta<
            TAccountProofQueueBatch,
            InstructionAccountInputAddress<TAccountProofQueueBatch>
        >,
        ResolvedInstructionAccountMeta<
            TAccountSystemProgram,
            InstructionAccountInputAddress<TAccountSystemProgram>
        >
    >
> {
    // Program address.
    const programAddress = config?.programAddress ?? TOKEN_PROGRAM_ADDRESS;

    // Account meta helper.
    const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

    // Original accounts.
    const originalAccounts = {
        payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
        state: {
            value: input.state ?? null,
            isSigner: false,
            isWritable: true,
        },
        proofQueueBatch: {
            value: input.proofQueueBatch ?? null,
            isSigner: false,
            isWritable: true,
        },
        systemProgram: {
            value: input.systemProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
    };
    const accounts = originalAccounts as Record<
        keyof typeof originalAccounts,
        ResolvedInstructionAccount
    >;

    // Original args.
    const args = { ...input };

    // Resolve default values.
    if (!accounts.state.value) {
        accounts.state.value = await findStatePda({ programAddress });
    }
    if (!accounts.systemProgram.value) {
        accounts.systemProgram.value =
            '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
    }

    return Object.freeze({
        accounts: [
            getAccountMeta('payer', accounts.payer),
            getAccountMeta('state', accounts.state),
            getAccountMeta('proofQueueBatch', accounts.proofQueueBatch),
            getAccountMeta('systemProgram', accounts.systemProgram),
        ],
        data: getUpdateInstructionDataEncoder().encode(
            args as UpdateInstructionDataArgs
        ),
        programAddress,
    } as UpdateInstruction<
        TProgramAddress,
        ResolvedInstructionAccountMeta<
            TAccountPayer,
            InstructionAccountInputAddress<TAccountPayer>
        >,
        ResolvedInstructionAccountMeta<
            TAccountState,
            InstructionAccountInputAddress<TAccountState>
        >,
        ResolvedInstructionAccountMeta<
            TAccountProofQueueBatch,
            InstructionAccountInputAddress<TAccountProofQueueBatch>
        >,
        ResolvedInstructionAccountMeta<
            TAccountSystemProgram,
            InstructionAccountInputAddress<TAccountSystemProgram>
        >
    >);
}

export type UpdateInput<
    TAccountPayer extends InstructionSignerInput = InstructionSignerInput,
    TAccountState extends InstructionAccountInput = InstructionAccountInput,
    TAccountProofQueueBatch extends InstructionAccountInput =
        InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput =
        InstructionAccountInput,
> = {
    payer: TAccountPayer;
    state: TAccountState;
    /**
     * (`state.proof_queue_batch_count`). Its address can only be checked
     * against state inside the handler, so seeds are derived and compared
     * there; it is created and written in handle_update only when the
     * update's batch drained at least one request, and ignored otherwise.
     */
    proofQueueBatch: TAccountProofQueueBatch;
    systemProgram?: TAccountSystemProgram;
    proof: UpdateInstructionDataArgs['proof'];
    sp1PublicInputs: UpdateInstructionDataArgs['sp1PublicInputs'];
};

export function getUpdateInstruction<
    TAccountPayer extends InstructionSignerInput,
    TAccountState extends InstructionAccountInput,
    TAccountProofQueueBatch extends InstructionAccountInput,
    TAccountSystemProgram extends InstructionAccountInput,
    TProgramAddress extends Address = typeof TOKEN_PROGRAM_ADDRESS,
>(
    input: UpdateInput<
        TAccountPayer,
        TAccountState,
        TAccountProofQueueBatch,
        TAccountSystemProgram
    >,
    config?: { programAddress?: TProgramAddress }
): UpdateInstruction<
    TProgramAddress,
    ResolvedInstructionAccountMeta<
        TAccountPayer,
        InstructionAccountInputAddress<TAccountPayer>
    >,
    ResolvedInstructionAccountMeta<
        TAccountState,
        InstructionAccountInputAddress<TAccountState>
    >,
    ResolvedInstructionAccountMeta<
        TAccountProofQueueBatch,
        InstructionAccountInputAddress<TAccountProofQueueBatch>
    >,
    ResolvedInstructionAccountMeta<
        TAccountSystemProgram,
        InstructionAccountInputAddress<TAccountSystemProgram>
    >
> {
    // Program address.
    const programAddress = config?.programAddress ?? TOKEN_PROGRAM_ADDRESS;

    // Account meta helper.
    const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');

    // Original accounts.
    const originalAccounts = {
        payer: { value: input.payer ?? null, isSigner: true, isWritable: true },
        state: {
            value: input.state ?? null,
            isSigner: false,
            isWritable: true,
        },
        proofQueueBatch: {
            value: input.proofQueueBatch ?? null,
            isSigner: false,
            isWritable: true,
        },
        systemProgram: {
            value: input.systemProgram ?? null,
            isSigner: false,
            isWritable: false,
        },
    };
    const accounts = originalAccounts as Record<
        keyof typeof originalAccounts,
        ResolvedInstructionAccount
    >;

    // Original args.
    const args = { ...input };

    // Resolve default values.
    if (!accounts.systemProgram.value) {
        accounts.systemProgram.value =
            '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
    }

    return Object.freeze({
        accounts: [
            getAccountMeta('payer', accounts.payer),
            getAccountMeta('state', accounts.state),
            getAccountMeta('proofQueueBatch', accounts.proofQueueBatch),
            getAccountMeta('systemProgram', accounts.systemProgram),
        ],
        data: getUpdateInstructionDataEncoder().encode(
            args as UpdateInstructionDataArgs
        ),
        programAddress,
    } as UpdateInstruction<
        TProgramAddress,
        ResolvedInstructionAccountMeta<
            TAccountPayer,
            InstructionAccountInputAddress<TAccountPayer>
        >,
        ResolvedInstructionAccountMeta<
            TAccountState,
            InstructionAccountInputAddress<TAccountState>
        >,
        ResolvedInstructionAccountMeta<
            TAccountProofQueueBatch,
            InstructionAccountInputAddress<TAccountProofQueueBatch>
        >,
        ResolvedInstructionAccountMeta<
            TAccountSystemProgram,
            InstructionAccountInputAddress<TAccountSystemProgram>
        >
    >);
}

export type ParsedUpdateInstruction<
    TProgram extends string = typeof TOKEN_PROGRAM_ADDRESS,
    TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
    programAddress: Address<TProgram>;
    accounts: {
        payer: TAccountMetas[0];
        state: TAccountMetas[1];
        /**
         * (`state.proof_queue_batch_count`). Its address can only be checked
         * against state inside the handler, so seeds are derived and compared
         * there; it is created and written in handle_update only when the
         * update's batch drained at least one request, and ignored otherwise.
         */
        proofQueueBatch: TAccountMetas[2];
        systemProgram: TAccountMetas[3];
    };
    data: UpdateInstructionData;
};

export function parseUpdateInstruction<
    TProgram extends string,
    TAccountMetas extends readonly AccountMeta[],
>(
    instruction: Instruction<TProgram> &
        InstructionWithAccounts<TAccountMetas> &
        InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateInstruction<TProgram, TAccountMetas> {
    if (instruction.accounts.length < 4) {
        throw new SolanaError(
            SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
            {
                actualAccountMetas: instruction.accounts.length,
                expectedAccountMetas: 4,
            }
        );
    }
    let accountIndex = 0;
    const getNextAccount = () => {
        const accountMeta = (instruction.accounts as TAccountMetas)[
            accountIndex
        ]!;
        accountIndex += 1;
        return accountMeta;
    };
    return {
        programAddress: instruction.programAddress,
        accounts: {
            payer: getNextAccount(),
            state: getNextAccount(),
            proofQueueBatch: getNextAccount(),
            systemProgram: getNextAccount(),
        },
        data: getUpdateInstructionDataDecoder().decode(instruction.data),
    };
}
