/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    combineCodec,
    fixDecoderSize,
    fixEncoderSize,
    getBytesDecoder,
    getBytesEncoder,
    getTupleDecoder,
    getTupleEncoder,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type ReadonlyUint8Array,
} from '@solana/kit';

/** 32 bytes; Borsh-encoded exactly as alloy's `B256`. */
export type Bytes32 = readonly [ReadonlyUint8Array];

export type Bytes32Args = Bytes32;

export function getBytes32Encoder(): FixedSizeEncoder<Bytes32Args> {
    return getTupleEncoder([fixEncoderSize(getBytesEncoder(), 32)]);
}

export function getBytes32Decoder(): FixedSizeDecoder<Bytes32> {
    return getTupleDecoder([fixDecoderSize(getBytesDecoder(), 32)]);
}

export function getBytes32Codec(): FixedSizeCodec<Bytes32Args, Bytes32> {
    return combineCodec(getBytes32Encoder(), getBytes32Decoder());
}
