/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    combineCodec,
    fixDecoderSize,
    fixEncoderSize,
    getBytesDecoder,
    getBytesEncoder,
    getTupleDecoder,
    getTupleEncoder,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type ReadonlyUint8Array,
} from '@solana/kit';

/** A 20-byte Ethereum address; Borsh-encoded exactly as alloy's `Address`. */
export type EthAddress = readonly [ReadonlyUint8Array];

export type EthAddressArgs = EthAddress;

export function getEthAddressEncoder(): FixedSizeEncoder<EthAddressArgs> {
    return getTupleEncoder([fixEncoderSize(getBytesEncoder(), 20)]);
}

export function getEthAddressDecoder(): FixedSizeDecoder<EthAddress> {
    return getTupleDecoder([fixDecoderSize(getBytesDecoder(), 20)]);
}

export function getEthAddressCodec(): FixedSizeCodec<
    EthAddressArgs,
    EthAddress
> {
    return combineCodec(getEthAddressEncoder(), getEthAddressDecoder());
}
