/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    combineCodec,
    fixDecoderSize,
    fixEncoderSize,
    getBytesDecoder,
    getBytesEncoder,
    getTupleDecoder,
    getTupleEncoder,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
    type ReadonlyUint8Array,
} from '@solana/kit';

/**
 * A 256-bit unsigned integer as 32 little-endian bytes; Borsh-encoded
 * exactly as alloy's `U256`.
 */
export type U256Le = readonly [ReadonlyUint8Array];

export type U256LeArgs = U256Le;

export function getU256LeEncoder(): FixedSizeEncoder<U256LeArgs> {
    return getTupleEncoder([fixEncoderSize(getBytesEncoder(), 32)]);
}

export function getU256LeDecoder(): FixedSizeDecoder<U256Le> {
    return getTupleDecoder([fixDecoderSize(getBytesDecoder(), 32)]);
}

export function getU256LeCodec(): FixedSizeCodec<U256LeArgs, U256Le> {
    return combineCodec(getU256LeEncoder(), getU256LeDecoder());
}
