/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
    combineCodec,
    getArrayDecoder,
    getArrayEncoder,
    getStructDecoder,
    getStructEncoder,
    getU8Decoder,
    getU8Encoder,
    type FixedSizeCodec,
    type FixedSizeDecoder,
    type FixedSizeEncoder,
} from '@solana/kit';
import {
    getBytes32Decoder,
    getBytes32Encoder,
    getEthAddressDecoder,
    getEthAddressEncoder,
    getU256LeDecoder,
    getU256LeEncoder,
    type Bytes32,
    type Bytes32Args,
    type EthAddress,
    type EthAddressArgs,
    type U256Le,
    type U256LeArgs,
} from './index.js';

export type VerifiedRequest = {
    target: EthAddress;
    collectionKeysCount: number;
    collectionKeys: Array<Bytes32>;
    value: U256Le;
};

export type VerifiedRequestArgs = {
    target: EthAddressArgs;
    collectionKeysCount: number;
    collectionKeys: Array<Bytes32Args>;
    value: U256LeArgs;
};

export function getVerifiedRequestEncoder(): FixedSizeEncoder<VerifiedRequestArgs> {
    return getStructEncoder([
        ['target', getEthAddressEncoder()],
        ['collectionKeysCount', getU8Encoder()],
        ['collectionKeys', getArrayEncoder(getBytes32Encoder(), { size: 2 })],
        ['value', getU256LeEncoder()],
    ]);
}

export function getVerifiedRequestDecoder(): FixedSizeDecoder<VerifiedRequest> {
    return getStructDecoder([
        ['target', getEthAddressDecoder()],
        ['collectionKeysCount', getU8Decoder()],
        ['collectionKeys', getArrayDecoder(getBytes32Decoder(), { size: 2 })],
        ['value', getU256LeDecoder()],
    ]);
}

export function getVerifiedRequestCodec(): FixedSizeCodec<
    VerifiedRequestArgs,
    VerifiedRequest
> {
    return combineCodec(
        getVerifiedRequestEncoder(),
        getVerifiedRequestDecoder()
    );
}
